modLoader = "javafml" #mandatory
loaderVersion = "[2,)" #mandatory
license = "LGPL-2.1"
[[mods]] #mandatory
modId = "l2library" #mandatory
version = "3.0.8" #mandatory
displayName = "L2Library" #mandatory
authors = "lcy0x1" #optional
description = '''Library mod for all L2 mods'''
[[mixins]]
config="l2library.mixins.json"
[[dependencies.l2library]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "[21.1.4,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.l2library]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"