modLoader = "javafml" #mandatory
loaderVersion = "[2,)" #mandatory
license = "LGPL-2.1"
[[mods]] #mandatory
modId = "l2tabs" #mandatory
version = "3.0.5+7" #mandatory
displayName = "L2Tabs" #mandatory
authors = "lcy0x1" #optional
description = '''Inventory Tabs'''
[[mixins]]
config="l2tabs.mixins.json"
[[dependencies.l2tabs]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "[21.0,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.l2tabs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
[[dependencies.l2tabs]]
modId = "accessories"
type = "optional"
versionRange = "[1.1.0-beta.5+1.21.1,)"
ordering = "NONE"
side = "BOTH"