#对话系统客户端配置
[dialog_client]

	#对话框UI配置
	[dialog_client.ui]
		#对话框宽度
		# Default: 320
		# Range: > 0
		dialogBoxWidth = 320
		#对话框高度
		# Default: 100
		# Range: > 0
		dialogBoxHeight = 100
		#对话框内边距
		# Default: 10
		# Range: > 0
		dialogBoxPadding = 10
		#对话文本默认颜色 (ARGB格式) 如：0xFFFFFFFF
		dialogTextColor = -1
		#对话框背景默认颜色 (RGB格式) 如：0x000000
		dialogBackgroundColor = 0
		#对话框背景不透明度 (0-255)
		# Default: 200
		# Range: > 0
		dialogBackgroundOpacity = 200
		#是否使用自定义按钮纹理（否则使用Minecraft原版按钮纹理）
		useCustomButtonTexture = false

	#立绘配置
	[dialog_client.portrait]
		#启用立绘动画
		enablePortraitAnimations = true

	#对话系统配置
	[dialog_client.system]
		#是否在对话时暂停游戏（仅单人模式）
		isPauseScreen = false
		#自动推进对话的延迟时间（毫秒）
		# Default: 700
		# Range: > 0
		autoAdvanceDelay = 700
		#是否显示说话者的名称
		showSpeakerName = true
		#文本逐字显示的速度（每秒字符数，设置为0则立即显示全部文本）
		# Default: 20
		# Range: 0 ~ 1000
		textAnimationSpeed = 20

	#覆层模式配置
	[dialog_client.overlay]
		#结束后是否在聊天窗口中显示对话记录
		showHistoryInChat = true
		#对话框宽度
		# Default: 200
		# Range: > 0
		overlayDialogBoxWidth = 200
		#对话框高度
		# Default: 45
		# Range: > 0
		overlayDialogBoxHeight = 45
		#对话框内边距
		# Default: 6
		# Range: > 0
		overlayDialogBoxPadding = 6
		#对话框Y轴位移
		# Default: 45
		# Range: > 0
		overlayDialogBoxOffsetY = 45
